-- Chat: conversations, their members, messages and what hangs on them.
-- Member and group ids are the Chest's (mbr_…, grp_…), never names. Every
-- text a member writes is sealed by the Chest (chest:sealed:1:…): bodies,
-- file names, drafts, descriptions. What stays in clear is what lists,
-- access, unread counts and notifications need.

create table conversations (
  id bigint generated always as identity primary key,
  kind text not null check (kind in ('public', 'private', 'direct')),
  -- a channel's name; none for a direct conversation
  name text check (name ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
  -- a channel's description, sealed (context about:<id>)
  about text,
  -- a direct conversation's people, sorted and joined by commas: one per set
  direct_key text,
  created_by text check (created_by ~ '^mbr_[a-z2-7]{26}$'),
  created_at timestamptz not null default now(),
  archived_at timestamptz,
  -- everyone joins it at their first visit
  is_default boolean not null default false,
  last_message_id bigint not null default 0,
  -- the last id written in it (messages, replies, the tool's lines): a
  -- write with a smaller one takes a new id, so ids follow commit order
  last_posted_id bigint not null default 0,
  last_message_at timestamptz,
  constraint conversation_shape check ((kind = 'direct') = (name is null) and (kind = 'direct') = (direct_key is not null))
);
create unique index conversations_name on conversations (name) where name is not null;
create unique index conversations_direct on conversations (direct_key) where direct_key is not null;

insert into conversations (kind, name, is_default) values ('public', 'general', true);

-- Who is in a conversation: the realtime's membership table (a row removed
-- takes its member out of the channel c:<id> at once). Only a change of
-- conversation_id or member_id counts as a removal: last_read, notify and
-- starred change freely.
create table conversation_members (
  conversation_id bigint not null references conversations on delete cascade,
  member_id text not null check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  -- added in person (or joined), beside any group of the conversation
  added boolean not null default true,
  joined_at timestamptz not null default now(),
  -- the last top-level message read
  last_read bigint not null default 0,
  notify text not null default 'default' check (notify in ('default', 'all', 'mentions', 'none')),
  starred boolean not null default false,
  primary key (conversation_id, member_id)
);
create index conversation_members_member on conversation_members (member_id);

-- Groups of the Chest given a conversation: their members are in it while
-- they are in the group.
create table conversation_groups (
  conversation_id bigint not null references conversations on delete cascade,
  group_id text not null check (group_id ~ '^grp_[a-z2-7]{26}$'),
  primary key (conversation_id, group_id)
);
create index conversation_groups_group on conversation_groups (group_id);

-- A member who left a conversation a group gives them: not added back by
-- the group until they join or are added again.
create table conversation_leaves (
  conversation_id bigint not null references conversations on delete cascade,
  member_id text not null check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  primary key (conversation_id, member_id)
);

create table messages (
  -- taken from its sequence before the body is sealed: the body's context
  -- is m:<id>
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references conversations on delete cascade,
  -- the root of the thread a reply belongs to
  thread_id bigint references messages on delete cascade,
  author text not null check (author ~ '^mbr_[a-z2-7]{26}$'),
  -- a member's message, or a line the tool writes (who joined, a rename)
  kind text not null default 'message' check (kind in ('message', 'created', 'joined', 'left', 'added', 'removed', 'renamed', 'about', 'archived', 'unarchived')),
  -- sealed (context m:<id>); '' once deleted, and for the tool's lines
  body text not null default '',
  -- the tool's lines: who was added or removed, a name's change
  meta jsonb,
  mentions text[] not null default '{}',
  mention_all boolean not null default false,
  mention_here boolean not null default false,
  has_files boolean not null default false,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  pinned_at timestamptz,
  pinned_by text check (pinned_by ~ '^mbr_[a-z2-7]{26}$'),
  reply_count integer not null default 0,
  last_reply_at timestamptz,
  -- the last people who replied, newest first, three at most
  repliers text[] not null default '{}',
  constraint reply_has_no_replies check (thread_id is null or reply_count = 0)
);
create index messages_conversation on messages (conversation_id, id) where thread_id is null;
create index messages_thread on messages (thread_id, id) where thread_id is not null;
create index messages_all on messages (conversation_id, id);
-- Messages that mention someone: unread mentions, the Mentions view.
create index messages_mentioning on messages (conversation_id, id) where thread_id is null and (mention_all or mentions <> '{}');
create index messages_thread_mentioning on messages (thread_id, id) where thread_id is not null and (mention_all or mentions <> '{}');
create index messages_any_mention on messages (id) where mention_all or mentions <> '{}';
create index messages_pinned on messages (conversation_id, pinned_at) where pinned_at is not null;

create table reactions (
  message_id bigint not null references messages on delete cascade,
  emoji text not null check (char_length(emoji) between 1 and 32),
  member_id text not null check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  conversation_id bigint not null references conversations on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, emoji, member_id)
);
create index reactions_member on reactions (member_id);

create table attachments (
  id bigint generated always as identity primary key,
  message_id bigint not null references messages on delete cascade,
  -- the Chest's name of the file object (u/<random>.<ext>)
  object text not null unique,
  -- the name the member gave it, sealed (context f:<object>)
  name text not null,
  type text not null,
  size bigint not null check (size >= 0),
  width integer,
  height integer,
  uploader text not null check (uploader ~ '^mbr_[a-z2-7]{26}$'),
  created_at timestamptz not null default now()
);
create index attachments_message on attachments (message_id);

create table saved (
  member_id text not null check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  message_id bigint not null references messages on delete cascade,
  created_at timestamptz not null default now(),
  primary key (member_id, message_id)
);
create index saved_latest on saved (member_id, created_at desc, message_id desc);

-- Threads a member follows: those they started, replied to or were
-- mentioned in, until they unfollow; the last reply they read.
create table thread_follows (
  message_id bigint not null references messages on delete cascade,
  member_id text not null check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  following boolean not null default true,
  last_read bigint not null default 0,
  primary key (message_id, member_id)
);
create index thread_follows_member on thread_follows (member_id) where following;

-- What a member wrote and did not send, per conversation and thread (0 for
-- none): sealed (context d:<member>:<conversation>:<thread>).
create table drafts (
  member_id text not null check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  conversation_id bigint not null references conversations on delete cascade,
  thread_id bigint not null default 0,
  body text not null,
  updated_at timestamptz not null default now(),
  primary key (member_id, conversation_id, thread_id)
);

-- A member's place: when they first came (the default channels joined
-- then), the conversation they had open.
create table people (
  member_id text primary key check (member_id ~ '^mbr_[a-z2-7]{26}$'),
  first_seen timestamptz not null default now(),
  last_conversation bigint
);

-- The Chest's deliveries already handled (events and schedule runs come at
-- least once).
create table handled (
  id text primary key,
  at timestamptz not null default now()
);
